[package]
name = "wuwa-beta-downloader"
version = "0.2.0"
authors = ["Alvin Null <supdrewin@outlook.com>"]
edition = "2021"
description = "WuWa Beta Downloader powered by Rust"
repository = "https://github.com/supdrewin/wuwa-beta-downloader/"
license = "MIT"

[dependencies]
base16ct = { version = "0.2.0", features = ["std"] }
clap = { version = "4.5.22", features = ["derive"] }
console = "0.15.8"
futures-util = "0.3.31"
indicatif = "0.17.9"
md-5 = "0.10.6"
num_cpus = "1.16.0"
reqwest = { version = "0.12.9", features = ["gzip", "json", "stream"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
