name: Rust

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  BINARY: wuwa-downloader.exe
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        cargo b -rv
        cp target/release/${{ env.BINARY }}
        $(get-filehash ${{ env.BINARY }}).hash.tolower() > ${{ env.BINARY }}.sha256
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.BINARY }}
          ${{ env.BINARY }}.sha256
